import type { Metadata } from "next";
import { Geist, Geist_Mono, Manrope, Public_Sans } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { StickyFooter } from "@/components/sections/layout/sticky-footer";

const manrope = Manrope({ subsets: ["latin"], variable: "--font-sans" });
const quicheSans = localFont({
  src: [
    {
      path: "./fonts/QuicheSans-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    { path: "./fonts/QuicheSans-Italic.woff2", weight: "400", style: "italic" },
    { path: "./fonts/QuicheSans-Bold.woff2", weight: "700", style: "normal" },
    {
      path: "./fonts/QuicheSans-BoldItalic.woff2",
      weight: "700",
      style: "italic",
    },
    { path: "./fonts/QuicheSans-Thin.woff2", weight: "100", style: "normal" },
    {
      path: "./fonts/QuicheSans-ThinItalic.woff2",
      weight: "100",
      style: "italic",
    },
  ],
  variable: "--font-quiche-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" className={`${manrope.variable} ${quicheSans.variable}`}>
      <body className={`${manrope.className} text-zinc-950 antialiased`}>
        {children}
        <StickyFooter />
      </body>
    </html>
  );
}
