import { Metadata } from "next";
import HomePageClient from "./client";

export const metadata: Metadata = {
  title: "SolarHome™ - Solutions de films solaires pour votre intérieur et extérieur",
  description: "Generated by create next app",
};

export default function HomePage() {
  return (
    <>
      <HomePageClient />
    </>
  );
}
